version: "3.7"


services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - soon_network
    volumes:
      - /home/breathin_x/nginx.conf:/etc/nginx/nginx.conf
      - soon_static:/data/static/
      - soon_media:/data/media/

  django:
    image: soon_django:5
    networks:
      - soon_network
    volumes:
      - soon_static:/home/web-app1/staticfiles/
      - soon_media:/home/web-app1/media/
    secrets:
      - django_secret_key
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - soon_network
    volumes:
      - soon_maria:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: django
      MARIADB_USER: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD: /run/secrets/MARIADB_PASSWORD

networks:
  soon_network:

volumes:
  soon_static:
  soon_media:
  soon_maria:

secrets:
  django_secret_key:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true